function [x, val, valHist, m] = remark(options)
m = market(options.objFun,...
    options.domain,...
    options.nDemander,...
    options.maxFrnd,...
    options.nDim,...
    options.nSupplier,...
    options.constrPer,...
    options.KsigmaD,...
    options.KsigmaS,...
    options.KnumS...
    );
nIter = floor(options.nFeval/options.nDemander);
valHist = zeros(nIter, 2);
for iter = 1:nIter
    hist = [m.dmd.bestPlace];
    [maxValue, iimax] = max([hist.value]);
    fprintf('FEVAL\t%d\t|\tVALUE\t%d\t\n', iter*options.nDemander, maxValue)
    valHist(iter, :) = [iter*options.nDemander, maxValue];
    if rem(iter, options.constrPer) == 0
        m = m.makeFrnd;
        m = m.supplierUpdate;
    end
    m = m.priceEval;
    m = m.demanderUpdate;
end
x = denorm(hist(iimax).loc, options.domain);
val = maxValue;
end
